# golangci-lint configuration
# Built by Digitalis.IO - https://digitalis.io/

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple and stylecheck)
    - unused        # Check for unused code
    - misspell      # Detect misspelled words
    - goconst       # Find repeated strings
    - gosec         # Security issues
    - revive        # Fast linter
    - unconvert     # Remove unnecessary type conversions
  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - shadow
    gosec:
      excludes:
        - G402  # We intentionally allow InsecureSkipVerify for monitoring
    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else

formatters:
  enable:
    - gofmt         # Check formatting
    - goimports     # Check import formatting

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
